from app.core.scoring_rule_loader import scoring_rule_loader

AXIS_CODES = scoring_rule_loader.get("axis_codes")
SCORE_RANGE = scoring_rule_loader.get("score_range")
NEUTRAL_COMPAT_SCORE = scoring_rule_loader.get("neutral_compat_score")
MIN_DATA_REQUIREMENTS = scoring_rule_loader.get("min_data_requirements")
CONFIDENCE_WEIGHTS = scoring_rule_loader.get("confidence_weights")
UAS_WEIGHTS = scoring_rule_loader.get("uas_weights")
SMS_WEIGHTS = scoring_rule_loader.get("sms_weights")
VOS_WEIGHTS = scoring_rule_loader.get("vos_weights")
SENTIMENT_THRESHOLDS = scoring_rule_loader.get("sentiment_thresholds")
DURATION_CONFIDENCE_VALUES = scoring_rule_loader.get("duration_confidence_values")
CLASSIFICATION_THRESHOLDS = scoring_rule_loader.get("classification_thresholds")
HARMFUL_KEYWORDS = scoring_rule_loader.get("harmful_keywords")
TOXIC_CATEGORY_KEYWORDS = scoring_rule_loader.get("toxic_category_keywords")
MAX_TOPIC_CATEGORIES = scoring_rule_loader.get("max_topic_categories")
CONCENTRATION_BETA = scoring_rule_loader.get("concentration_beta")
EDUCATIONAL_CATEGORIES = set(scoring_rule_loader.get("educational_categories"))
